# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 32 # def: 256

# Directories
# train_folder: /scratch/ilsvrc12/train_hkl_b256_b_256/
# val_folder: /scratch/ilsvrc12/val_hkl_b256_b_256/
train_folder: /home/ubuntu/DL/Images/ImageNet/OutputKylberg/tar_root_dir/train_hkl_b32_b_32/
val_folder: /home/ubuntu/DL/Images/ImageNet/OutputKylberg/tar_root_dir/val_hkl_b32_b_32/